packages:
  - packages/*
  - examples/*
  - examples/*/*
  - examples/*/*/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - utf-8-validate
