packages:
  - 'packages/*'
  - 'examples/*'
  - 'examples/*/*'
  - 'examples/*/*/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
